kind: pipeline
name: default

type: docker
steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --enable-all
  - name: migration
    image: golang
    commands:
      - go run main.go migrate
    environment:
      MONITOR_DB_HOST: "database"
      MONITOR_DB_PORT: 5432
  - name: test
    image: golang
    commands:
      - go test -v ./... -covermode=atomic -coverprofile=coverage.out
    environment:
      MONITOR_DB_HOST: "database"
      MONITOR_DB_PORT: 5432
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - coverage.out

services:
  - name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitor